version: '3'
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    volumes:
      - ./database/data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - clickhouse_net
#    deploy:
#      resources:
#        limits:
#          cpus: '0.4'
#          memory: 2G
networks:
  clickhouse_net:
    driver: bridge